name: bencliff
favicon: null
layout_spectrum: 1
typography_spectrum: 0.51832
title: 'This is Me!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#404040'
    - '#f6f6f8'
    - '#518d8d'
    - '#656469'
    - '#a1a1a3'
  brandStrength: 0
  lightness: 0
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
