name: bencliff
favicon: null
layout_spectrum: 1
typography_spectrum: 0.51832
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafafa'
    - '#ff7e81'
    - '#dfb6fa'
    - '#4f56f5'
    - '#ff424a'
  brandStrength: 0.125
  lightness: 0.875
  saturation: 0.4375
  rhythmicContrast: 0
purpose: []
